"""empty message

Revision ID: 29bca20b2dc6
Revises: 4a727af5ff3f
Create Date: 2022-09-12 22:02:21.725819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29bca20b2dc6'
down_revision = '4a727af5ff3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_lading_page', sa.Column('show', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_lading_page', 'show')
    # ### end Alembic commands ###
