"""empty message

Revision ID: 37f2a7bbdb9a
Revises: 9bd3b3c817c8
Create Date: 2022-09-12 22:37:52.479089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f2a7bbdb9a'
down_revision = '9bd3b3c817c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_lading_page', sa.Column('show', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_lading_page', 'show')
    # ### end Alembic commands ###
