"""empty message

Revision ID: 4a727af5ff3f
Revises: 64129e0ec59e
Create Date: 2022-09-06 21:32:51.356970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a727af5ff3f'
down_revision = '64129e0ec59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_lading_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_1', sa.String(length=120), nullable=False),
    sa.Column('image_2', sa.String(length=120), nullable=False),
    sa.Column('image_3', sa.String(length=120), nullable=False),
    sa.Column('info_1', sa.String(length=120), nullable=False),
    sa.Column('info_2', sa.String(length=120), nullable=False),
    sa.Column('info_3', sa.String(length=120), nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('Subtitulo', sa.String(length=80), nullable=False),
    sa.Column('video', sa.String(length=80), nullable=False),
    sa.Column('tips_1', sa.String(length=80), nullable=False),
    sa.Column('tips_2', sa.String(length=80), nullable=False),
    sa.Column('tips_3', sa.String(length=80), nullable=False),
    sa.Column('tips_4', sa.String(length=80), nullable=False),
    sa.Column('tips_5', sa.String(length=80), nullable=False),
    sa.Column('tips_6', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_lading_page')
    # ### end Alembic commands ###
