"""empty message

Revision ID: 70e32b63149a
Revises: d4594bfcddb2
Create Date: 2022-09-12 22:44:08.967707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e32b63149a'
down_revision = 'd4594bfcddb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_lading_page', sa.Column('show', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_lading_page', 'show')
    # ### end Alembic commands ###
