"""empty message

Revision ID: 9bd3b3c817c8
Revises: 29bca20b2dc6
Create Date: 2022-09-12 22:22:09.509102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd3b3c817c8'
down_revision = '29bca20b2dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_lading_page', sa.Column('show', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_lading_page', 'show')
    # ### end Alembic commands ###
