"""empty message

Revision ID: d4594bfcddb2
Revises: 37f2a7bbdb9a
Create Date: 2022-09-12 22:40:41.992188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4594bfcddb2'
down_revision = '37f2a7bbdb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_lading_page', sa.Column('show', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_lading_page', 'show')
    # ### end Alembic commands ###
